#!/bin/sh
# meta-custom/recipes-core/busybox/files/busybox-httpd

case "$1" in
    start)
        /sbin/httpd -h /srv/busybox-www -p 8080
        ;;
    stop)
        killall httpd
        ;;
    restart|reload)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
