ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
interface=wlan1
driver=nl80211

# WPA2-AES encryption
ssid=digi-wlan1-372e
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
wpa_passphrase=digiconnectcore

# IEEE 802.11ac
hw_mode=a
ieee80211n=1
ieee80211ac=1
ieee80211ax=1

# Channel
channel=165

# performance optimization
wmm_enabled=1

# Region/Country
ieee80211d=1
ieee80211h=1
country_code=US
