ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
interface=wlan1
driver=nl80211

# WPA2-AES encryption
ssid=digi-wlan1-##MAC##
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
wpa_passphrase=digiconnectcore

# IEEE 802.11ac
hw_mode=a
ieee80211ax=1
channel=0      # enable ACS（0 stands for auto select channel）

# ACS
ieee80211h=1   # enable DFS

# performance optimization
wmm_enabled=1
