# interface define
interface=wlan1
driver=nl80211

# SSID and country 
ssid=ap-digiccmp25
country_code=US

# configure 5GHz and WiFi 6, enable acs
hw_mode=a
ieee80211ax=1
channel=0      # enable ACS（0 stands for auto select channel）

# ACS
ieee80211d=1   # enable country code
ieee80211h=1   # enable DFS

# Channel width (20/40/80/160 MHz）
vht_oper_chwidth=0  # 0=20/40MHz, 1=80MHz, 2=160MHz
he_oper_chwidth=0

# HE (WiFi 6) configure
he_bss_color=1  # BSS color, reduce interference
he_mu_mimo=1    # enable multiple clients MIMO 

# security（ WPA3 or WPA2/WPA3 hybrid）
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK WPA-PSK-SHA256 SAE
wpa_passphrase=digi-connectcore
wpa_pairwise=CCMP
rsn_pairwise=CCMP

# performance optimization
wmm_enabled=1
ht_capab=[SHORT-GI-20]
vht_capab=[MAX-MPDU-11454][RXLDPC][SHORT-GI-20][TX-STBC][RX-STBC1]
he_capab=[HE20][HE-MCS-0-11][HE-MAC-CAP0][HE-PHY-CAP0]
